### ISSUE TITLE
module 'psutil' has no attribute 'network_io_counters'

### ISSUE THREAD

**Issue by W-quan** [fossfreedom/indicator-sysmonitor#45] opened 2016-04-22 02:05 UTC
When i try to use net, it show me that. How to fix it?  My OS is ubuntu 16.04.

**Comment by fossfreedom** [comment] 2016-04-22 08:04
duplicate of this - https://github.com/fossfreedom/indicator-sysmonitor/issues/40

I'll try to find some time next week to upload the latest development version into the PPA.

**Closed by fossfreedom** 2016-04-22 08:04 UTC
